### ISSUE TITLE
Why do some class names begin in lower case?

### ISSUE THREAD

**Issue by xissburg** [Ybalrid/Ogre_glTF#26]
I am in the process of refactoring, cleaning up and changing a few things in this project, and am also implementing new features. I'll submit a pull request later though I'm not sure all my changes will be welcome.

One thing I'm trying to understand and am feeling the urge to change are certain class names that begin in lower case, e.g. `loaderAdapter`, `modelConverter`, `materialLoader`, `skeletonImporter`, `textureImporter`. Why's that and should I just go ahead and capitalize them?

**Comment by Ybalrid** [comment]
I think it's not *some* but *all* the non-ogre classes defined in this project are named like that. So let's just say it's consistent "as is"... ^^"

**Comment by xissburg** [comment]
Because it's quite unusual to have class names start in lower case and I think that makes the code look confusing.

**Comment by Ybalrid** [comment]
> Because it's quite unusual to have class names start in lower case 

Well, depend on who's co-debase we're talking about 🤷‍♂ 

For instance, the C++ standard library is fully `snake_case`. There's no conventions, we are not in the Java world. 

My opinion is that if it's consistent it's okay. In my more recent project all my classes are also in `snake_case`, but I don't attach too much importance to this.

I don't think renaming *all* the classes in a library to change capitalization of the name is of any use.

Other than that, contributions are more than welcome. 

> I'll submit a pull request later though I'm not sure all my changes will be welcome.

This library is a really "early stage" project. Treat that like a version`0.2.somthing-pre-pre-pre-pre-alpha` 😂 There are many things that could be improved. There are many missing features. This is only finding and loading a single mesh inside the glTF hierarchy, and it's lacking features. The Texture loader is resource wasteful and many, many more things that I am not happy about when I look at this library. 

The only main design goal was to hide the header only libraries used internally to the user. This explains the pimpl based architecture.

It was thrown together hastily because I just needed to be able to *load something out of blender with a PBR material* and I was frustrated with the lack of Ogre 2.0 .mesh support in late 2017.

Obviously keep patches for Pull Request easy to process by making them touch one feature and work by themselves and if they improve something, they are probably worth being merged :wink:

**Comment by xissburg** [comment]
Ok I will try to get comfortable with the lower case class names for now. Thanks 🙃
